services:
  api:
    build: .
    ports:
      - "80:8000"
    environment:
      - whatsapp_service_url=${whatsapp_service_url}
      - whatsapp_secret_key=${whatsapp_secret_key}
    depends_on:
      - whatsapp

  whatsapp:
    build: ./whatsapp-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - webhook_url=${webhook_url}
      - whatsapp_secret_key=${whatsapp_secret_key}
    volumes:
      - builderbot_data:/app/.builderbot

volumes:
  builderbot_data:
