version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    restart: unless-stopped
