version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ip=168.75.100.151
      - whatsapp_service_url=http://167.234.238.64:3000
    env_file:
      - .env.production
    depends_on:
      - db

  whatsapp:
    build:
      context: .
      dockerfile: Dockerfile.whatsapp
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://168.75.100.151:8000
    env_file:
      - .env.production
    volumes:
      - ./auth_info:/app/auth_info

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
